# Generated by Django 2.2.5 on 2019-11-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName', max_length=128)),
                ('is_group_chat', models.BooleanField(default=False, verbose_name='Group chat')),
                ('last_message', models.TextField(null=True, verbose_name='Last message')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message', models.TextField(null=True, verbose_name='Last read message')),
                ('chat', models.ManyToManyField(to='chats.Chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
