# Generated by Django 2.2.5 on 2019-12-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName', max_length=128, verbose_name='Title chat')),
                ('is_group_chat', models.BooleanField(default=False, verbose_name='Group chat')),
                ('chat_avatar', models.ImageField(default='default.png', upload_to='', verbose_name='Avatar of chat')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat')),
            ],
        ),
    ]
