# Generated by Django 2.2.5 on 2019-12-10 17:12

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20191205_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_avatar',
            field=models.ImageField(default='default/default.png', upload_to=chats.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='NoName', max_length=128),
        ),
    ]
