# Generated by Django 2.2.5 on 2019-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='Second name')),
                ('nick', models.CharField(max_length=128, verbose_name='Nickname')),
                ('avatar', models.FilePathField(null=True, verbose_name='Path to avatar')),
                ('date_of_birthday', models.DateField(null=True, verbose_name='Date of birthday')),
            ],
        ),
    ]
