# Generated by Django 2.2.5 on 2019-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191111_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(verbose_name='Path to avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birthday',
            field=models.DateField(verbose_name='Date of birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=128, verbose_name='Nickname'),
        ),
    ]
