# Generated by Django 2.2.5 on 2019-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191112_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birthday',
            field=models.DateField(null=True, verbose_name='Date of birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Second name'),
        ),
    ]
