# Generated by Django 2.2.5 on 2019-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('I', 'IMAGE'), ('F', 'FILE')], max_length=1, verbose_name='Type attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
