# Generated by Django 2.2.5 on 2019-12-05 20:12

from django.db import migrations, models
import django.db.models.deletion
import message.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'IMAGE'), ('D', 'DOCUMENT'), ('A', 'AUDIO')], default='D', max_length=1, verbose_name='Type attachment')),
                ('file', models.FileField(max_length=10485760, null=True, upload_to=message.models.user_directory_path)),
                ('image', models.ImageField(max_length=5242880, null=True, upload_to=message.models.user_directory_path)),
                ('audio', models.FileField(max_length=5242880, null=True, upload_to=message.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Text of message')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Time published')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat')),
            ],
            options={
                'ordering': ('-added_at',),
            },
        ),
    ]
