# Generated by Django 2.2.5 on 2019-12-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191201_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-added_at',)},
        ),
    ]
