# Generated by Django 2.2.5 on 2019-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191112_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dialog',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='userman',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(verbose_name='Time published'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Text of message'),
        ),
    ]
