# Generated by Django 2.2.5 on 2019-11-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191112_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'IMAGE'), ('F', 'FILE')], max_length=1, verbose_name='Type attachment')),
                ('url', models.URLField(verbose_name='URL')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
            ],
        ),
    ]
