# Generated by Django 2.2.5 on 2019-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191216_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
