# Generated by Django 2.2.5 on 2019-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191210_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
